config/routes.rb
Rails.application.routes.draw do

  resources :restaurants

  get 'reviews', to: 'restaurants#reviews'

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
require_relative '../services/reviews_finder'

class RestaurantsController < ApplicationController

  def index
    if $error
      $error_message = "We couldn't find a restaurant matching that name, check the spelling and try again."
    else
      $error_message = nil
    end
    $error = nil
  end

  def reviews
    $error = nil

    # Limit search to Toronto
    city = "Toronto"

    # Use Yelp API to check if restaurant exists
    yelp_response = Yelp.client.search( city, { term: params[:restaurant], category_filter: "restaurants,bars,cafes", limit: 5 })

    if yelp_response.total == 0
      $error = true
      redirect_to '/'
    else
      # Use service to scrape data
      @data = ReviewsFinder.find_reviews(yelp_response)
    end

  end

  def contact
  end

  def show

  end

  def new

  end

  def edit

  end

  def create

  end

  def update
]
  end

  def destroy

  end

  protected

  def restaurant_params
    params.require(:restaurant).permit(
      :name, :address, :price_range, :cuisine, :city
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oh SNAP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css' %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css' %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width initial-scale=1.0, user-scalable=yes">
  <meta name="description" content="Every Toronto restaurant review in one place.">
</head>
<body>



<%= yield %>



</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div id="banner"></div>
<div class="container">


  <h1 id="title"><em> oh, snap!</em></h1>

  <h3 id="blurb">See what the people are saying.</h3>

  <div id="spacer">
    <form action="/reviews" method="get" id="search">
      <h5>Find reviews for any Toronto restaurant:</h5>
      <input type="text" name="restaurant" id="restaurant" required>
      <input type="submit" class="button-primary" value="Search" id="search-btn">
    </form>

    <div id="loading">
      <h5>Retrieving reviews...</h5>
      <i class="fa fa-refresh fa-spin" style="font-size:60px"></i>
    </div>
  </div>



  <div id="front-logos">
    <p>With reviews from:</p>
    <ul>
      <li><%= image_tag("yelp-invert.png", height: '40px', alt: 'yelp-logo') %></li>
      <li><%= image_tag("opentable-invert.png", height: '40px', alt: 'opentable-logo') %></li>
      <li><%= image_tag("zomato-invert.png", height: '50px', alt: 'zomato-logo') %></li>
      <li><%= image_tag("bookenda-invert.png", height: '40px', alt: 'bookenda-logo') %></li>
    </ul>
  </div>

<% if $error_message %>
  <div id="error-message">
    <h3> <%= $error_message %> </h3>
  </div>
<% end %>




</div>

app/views/restaurants/new.html.erb
<h1><%= @response.businesses[0].name %></h1>
<% i = 1 %>
<% until i == @response.businesses.length %>
  <h4><%= @response.businesses[i].name %></h4>
  <% i += 1 %>
<% end %>

app/views/restaurants/reviews.html.erb
<div class="row">
  <div id="sidebar" class="six columns">

    <a href="/"><i class="fa fa-arrow-circle-left" id="back"></i></a>

    <div id="restaurant-info">
      <div>
        <h1><%= @data[:restaurant][:name] %> </h1>
        <h4><%= @data[:restaurant][:address][0] %></h4>
        <h4><%= @data[:restaurant][:address][1] %></h4>
        <h4><%= @data[:restaurant][:address][2] %></h4>
      </div>
    </div>

    <div id="logos">
      <h6>Jump to reviews from:</h6>
      <%= image_tag("yelp.png", height: '40px', id: 'yelp-link', alt: 'yelp-logo') %>
      <%= image_tag("opentable.png", height: '40px', id: 'opentable-link', alt: 'opentable-logo') %>
      <%= image_tag("zomato.png", height: '50px', id: 'zomato-link', alt: 'zomato-logo') %>
      <%= image_tag("bookenda.png", height: '40px', id: 'bookenda-link', alt: 'bookenda-logo') %>
    </div>
  </div>

  <div id="reviews" class="six columns">
    <div id="yelp" class="review">
      <%= link_to image_tag("yelp-invert.png", height: '40px', alt: 'yelp logo'), @data[:reviews][:yelp][:url] %>
      <% for i in 0..@data[:reviews][:yelp][:reviews].length-1 %>
        <div>
          <p class="date"><%= @data[:reviews][:yelp][:dates][i] %></p> <p class="rating"> <%= @data[:reviews][:yelp][:ratings][i] %>/5</p>
          <p class="more"><%= @data[:reviews][:yelp][:reviews][i].html_safe %></p>
        </div>
      <% end %>
    </div>

    <div id="opentable" class="review">
      <%= link_to image_tag("opentable-invert.png", height: '40px', alt: 'opentable-logo'), @data[:reviews][:opentable][:url] %>
      <% if @data[:reviews][:opentable][:ratings] %>
        <% for i in 0..@data[:reviews][:opentable][:reviews].length-1 %>
          <div>
            <p class="date"><%= @data[:reviews][:opentable][:dates][i] %> </p> <p class="rating"><%= @data[:reviews][:opentable][:ratings][i] %>/5</p>
            <p class="more"><%= @data[:reviews][:opentable][:reviews][i].html_safe %></p>
          </div>
        <% end %>
      <% else %>
        <p> No OpenTable reviews for this restaurant.</p>
      <% end %>
    </div>

    <div id="zomato" class="review">
      <%= link_to image_tag("zomato-invert.png", height: '50px', alt: 'zomato-logo'), @data[:reviews][:zomato][:url] %>
      <% if @data[:reviews][:zomato][:ratings] %>
        <% for i in 0..@data[:reviews][:zomato][:reviews].length-1 %>
          <div>
            <p class="date"><%= @data[:reviews][:zomato][:dates][i] %></p> <p class="rating"><%= @data[:reviews][:zomato][:ratings][i] %>/5</p>
            <p class="more"><%= @data[:reviews][:zomato][:reviews][i].html_safe %></p>         
          </div>
        <% end %>
      <% else %>
        <p> No Zomato reviews for this restaurant.</p>
      <% end %>
    </div>

    <div id="bookenda" class="review">
      <%= link_to image_tag("bookenda-invert.png", height: '40px', alt: 'bookenda-logo'), @data[:reviews][:bookenda][:url] %>
      <% if @data[:reviews][:bookenda][:ratings] %>
        <% for i in 0..@data[:reviews][:bookenda][:reviews].length-1 %>
          <div>
            <p class="date"><%= @data[:reviews][:bookenda][:dates][i] %></p> <p class="rating"><%= @data[:reviews][:bookenda][:ratings][i] %>/5</p>
            <p class="more"><%= @data[:reviews][:bookenda][:reviews][i].html_safe %></p>
          </div>
        <% end %>
      <% else %>
        <p> No Bookenda reviews for this restaurant.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<%= link_to "Back to Search", restaurants_path %>

<h1></h1>